version: "3.4"
services:
  web:
    ports:
      - "3000:3000"
    image: researcher:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "sit-api.uap.universityapp.net/researcher/"
    container_name: researcher-dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
# networks:
#   default:
#     external: true
#     name: reverse-proxy